name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Commit .next build
        run: |
          git config user.email "your@email.com"
          git config user.name "GitHub Actions"
          git add .next/ -f
          git commit -m "build: update .next"
          git push
